services:
  database:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  webserver:
    container_name: php-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - 4000:80
    depends_on:
      - database
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adminServer@email.com
      PGADMIN_DEFAULT_PASSWORD: 1D4sNQ75J@c
    ports:
      - "5000:80"
    volumes:
      - pgadmin_db:/var/lib/pgadmin
    depends_on:
      - database
volumes:
  pgadmin_db:
