services:
  webserver:
    container_name: php-webserver
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./app:/var/www/html 
    ports:
      - 4000:80
    depends_on:
    - postgres


  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: .UYr930Qr
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adminServer@email.com
      PGADMIN_DEFAULT_PASSWORD: 1D4sNQ75J@c
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  pgadmin_data:
