# we define the services that we want to run
services:

  # Apache webserver service using a vulnerable PHP version
  webserver:
    container_name: php-webserver

    # Build the image using the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./app:/var/www/html 
    
    # Map port 4000 on the host to port 80 on the container
    ports:
      - 4000:80
    depends_on:
    - postgres

  # PostgreSQL database service
  postgres:
    image: postgres:16.0
    container_name: postgres

    # Set the environment default variables for the database (password is default for demonstration purposes only) 
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: .UYr930Qr
    
    # Map port 5432 on the host to port 5432 on the container
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  # pgAdmin service for managing the PostgreSQL database
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin

    # Set the default email and password for pgAdmin 4
    environment:
      PGADMIN_DEFAULT_EMAIL: adminServer@email.com
      PGADMIN_DEFAULT_PASSWORD: 1D4sNQ75J@c
    
    # Map port 5050 on the host to port 80 on the container
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  pgadmin_data:
